### ISSUE TITLE
Cannot install on Windows, Atom 1.17.0

### ISSUE THREAD

**Issue by vasily-kirichenko** [aergonaut/languageserver-rust#1]
```
Installing “languageserver-rust@0.1.0” failed.Hide output…

> atom-languageclient@0.1.0 postinstall C:\Users\vaski\AppData\Local\Temp\apm-install-dir-117420-12016-q767yk.5ik0muz0k9\node_modules\languageserver-rust\node_modules\atom-languageclient
> postinstall-build --only-as-dependency build "npm run compile"


> atom-languageclient@0.1.0 postinstall C:\Users\vaski\AppData\Local\Temp\apm-install-dir-117420-12016-q767yk.5ik0muz0k9\node_modules\languageserver-rust\node_modules\atom-languageclient
> postinstall-build --only-as-dependency build "npm run compile"


> atom-languageclient@0.1.0 prepublish C:\Users\vaski\AppData\Local\Temp\apm-install-dir-117420-12016-q767yk.5ik0muz0k9\node_modules\languageserver-rust\node_modules\atom-languageclient
> npm run clean && npm run compile


> atom-languageclient@0.1.0 clean C:\Users\vaski\AppData\Local\Temp\apm-install-dir-117420-12016-q767yk.5ik0muz0k9\node_modules\languageserver-rust\node_modules\atom-languageclient
> rm -rf build


(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26444) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
'rm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\vaski\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\vaski\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "clean"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! atom-languageclient@0.1.0 clean: `rm -rf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-languageclient@0.1.0 clean script 'rm -rf build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-languageclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-languageclient
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-languageclient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vaski\AppData\Local\Temp\apm-install-dir-117420-12016-q767yk.5ik0muz0k9\node_modules\languageserver-rust\node_modules\atom-languageclient\npm-debug.log

npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\vaski\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\vaski\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--only=dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! atom-languageclient@0.1.0 prepublish: `npm run clean && npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-languageclient@0.1.0 prepublish script 'npm run clean && npm run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-languageclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-languageclient
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-languageclient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vaski\AppData\Local\Temp\apm-install-dir-117420-12016-q767yk.5ik0muz0k9\node_modules\languageserver-rust\node_modules\atom-languageclient\npm-debug.log
{ Error: Command failed: C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\Users\vaski\AppData\Local\atom\app-1.17.0\resources\app\apm\bin\node.exe" "C:\Users\vaski\AppData\Local\atom\app-1.17.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" install --only=dev"

    at ChildProcess.<anonymous> (C:\Users\vaski\AppData\Local\Temp\apm-install-dir-117420-12016-q767yk.5ik0muz0k9\node_modules\languageserver-rust\node_modules\postinstall-build\index.js:53:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /d /s /c ""C:\\Users\\vaski\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\vaski\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" install --only=dev"' }
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\vaski\AppData\Local\Temp\apm-install-dir-117420-12016-q767yk.5ik0muz0k9\package.json'
npm WARN apm-install-dir-117420-12016-q767yk.5ik0muz0k9 No description
npm WARN apm-install-dir-117420-12016-q767yk.5ik0muz0k9 No repository field.
npm WARN apm-install-dir-117420-12016-q767yk.5ik0muz0k9 No README data
npm WARN apm-install-dir-117420-12016-q767yk.5ik0muz0k9 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\vaski\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\vaski\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\vaski\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\vaski\\.atom\\.apmrc" "install" "C:\\Users\\vaski\\AppData\\Local\\Temp\\d-117420-12016-1e5boc9.32hrwtrzfr\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-languageclient@0.1.0 postinstall: `postinstall-build --only-as-dependency build "npm run compile"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-languageclient@0.1.0 postinstall script 'postinstall-build --only-as-dependency build "npm run compile"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-languageclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     postinstall-build --only-as-dependency build "npm run compile"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-languageclient
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-languageclient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vaski\AppData\Local\Temp\apm-install-dir-117420-12016-q767yk.5ik0muz0k9\npm-debug.log
```

**Comment by chpio** [comment]
looks like it's an [atom-languageclient](https://github.com/atom/atom-languageclient) issue

**Comment by damieng** [comment]
It's not Windows specific - atom-languageclient had not yet been published because it was still in developer preview.

In order to unblock a few people I have gone ahead and published it for now as 0.1.1.  You'll need to bump your package.json.

I'd recommend using specific versions for now as we'll probably break a few times before 1.0.0 as things stabilize and then after that we'll adopt a semver (if I do that now we'd probably end up on 5.x.y before launch)

**Comment by aergonaut** [comment]
I updated the package to use the version of atom-languageclient from NPM

**Comment by damieng** [comment]
atom-languageclient has been published since then - you should be able to just specify the version you want (I'd specify an exact version number for now until we hit 1.0.0 in case we break stuff)
